gitbrent/PptxGenJS

- dist/pptxgen.js
Images are getting displayed on wrong slides because references are getting assigned incorrectly if adding images not sequentially to slides: for example if add image1 to slide2 and then image2 to slide1, they'll be displayed in wrong order.
> Fixing resource references

- dist/pptxgen.js
PptxGen detects incorrect shadow options values but the correction does not work (invalid PPTX produced). This PT assigns the corrected values to the proper object.
> Shadow corrections bugfix

- README.md
- dist/pptxgen.js
Sometimes, you don't necessarily need to get a file directly on save. Instead, it can be useful to have an opportunity to adjust the result generated by the library (to post-process it, add extra files or put the file into an archive). 
As the JSZip library provides an option to specify output type, I've added this option to the `save` method as well.
> Optional output type

- dist/pptxgen.js
Added an `escapeXmlEntities` function to escape XML reserved characters and use it wherever labels are being added to xml.  Otherwise we end up with invalid XML.
> Escape XML reserved characters so that we don't create invalid xml

- dist/pptxgen.js
This enhancement prevents silent fallbacking invalid color values to black. Now, if the passed color value does not match hexa RGB format or is not one of the listed scheme colors, a warning appears in console.
The fallback stays the same (black color), however developer is notified of passing invalid value.
> Color validation

- README.md
- dist/pptxgen.js
Currently, only axis ticks frequency can be controlled. This PR adds options to set even its labels frequency independently on ticks.
> Charts: catAxisLabelFrequency property added

- README.md
- dist/pptxgen.js
This feature enables resizing and cropping images. There are three options available – `cover` and `contain` that work the same as CSS property `background-size` and `crop` option that simply cuts off a part of an image (details in readme section _Image Sizing_). 
When this transformation option is used, the original image size (specified by `w` and `h` image properties) still stays unchanged, only image viewport changes. Thus, user can discard or adjust the transformation in PowerPoint.
Note: This PR **does not** solve issue #87.
> Image sizing

- dist/pptxgen.js
Hi Brent,
Ran into a problem trying to get multi line charts to work.  The attached example ([multi.zip](https://github.com/gitbrent/PptxGenJS/files/1341981/multi.zip)) starts with the docs example but I noticed that I kept getting a purple line for my secondary axis:
with this change I can get the black line that I was looking for:
> Line chart series colors were not being respected

- dist/pptxgen.js
This change should make `false` values for `catAxisLineShow` and `valAxisLineShow` properly hide the axis lines.  I attempted to match the already-existing documented functionality for these options, so no change should be needed to the README.
> Fix for Issue #231

- README.md
- dist/pptxgen.js
I added in a new option, `legendColor`.  It behaves similarly to other color options in that it takes a hex color value.  If nothing is specified, PowerPoint seems to always default the color to black.
> Update for Issue #233

- dist/pptxgen.js
the `value || ""` replacement was making 0 values replaced by '' (the empty string) instead of keeping 0 which is a valid value.
> Fix error that causes 0 values to be the empty string

- dist/pptxgen.js
With my [lab](https://github.com/hapijs/lab) testing I get the following error: `The following leaks were detected:intPosX, intPosY, intWidth, intHeight, objHyperlink, strImageData, strImagePath`
Seems like after the change the variables should be isolated for the local scope.
**OLD**:
`: addImageDefinition: function addImageDefinition(strImagePath, intPosX, intPosY, intWidth, intHeight, strImageData, target) {`
**NEW**:
`: addImageDefinition: function addImageDefinition(objImage, target) {`
How can I make this PR acceptable for merge and new version release?
> Isolate variables to the local scope

- dist/pptxgen.js
In Microsoft PowerPoint 2007, even the absence of <title> tag in xml on setting showTitle=false is creating a title by default with a value of 'name' key of the JSON input. This can be fixed by setting <c:autoTitleDeleted val="1"/> tag when rel.opts.showTitle is false. 
This problem does not exist in the later versions of PowerPoint but is present in PowerPoint 2007 and the fix works at all places.
> Fixed Title display on showTitle = false error

- dist/pptxgen.js
- examples/pptxgenjs-demo.html
- examples/pptxgenjs-demo.js
It adds the Radar chart feature.
Most of the existing chart options should be well rendered.
- The following option is specific:
Name | Description
-- | --
`radarStyle` | `standard` (default),`marker`, `filled`
An example of Radar charts is added in the HTML demo file. (Slide 15 of charts). 
The generated file is OOXML valid and seems to open well with Microsoft Powerpoint 2010 ;)
> Add radar chart implementation

- dist/pptxgen.js
I know this works for my cases, but I'd like someone else who's using PptxGenJS in Angular to test this out.
> Added better NodeJS checking and better support for Angular

- dist/pptxgen.js
I don't know why but this $.each don't work in a node/react app.
It triggers an error and prevent the file to be generated and saved
> Replace jquery each by standard forEach

- dist/pptxgen.js
Fixes a bug on scatter charts where if either the X or Y value was a 0, the data would be ignored and the plot point not shown on the chart.
> BugFix: 0 value plot points ignored on Scatter Chart

- dist/pptxgen.js
"$" symbol is reserved for usage in other web-applications (e.g. SharePoint for me). So it is better to use more specific synonym "jQuery". For me using $ breaks only pptxgenjs, for others it may break their own apps.
> BugFix: using $ for jQuery leads to conflict with code of some applications

- dist/pptxgen.js
By default we add only "jpeg" into presentation's content types (see makeXmlContTypes function) but Office365 definitely expects to see "jpg" also and consider some presentations as corrupted depending on certain pictures inserted.
> BugFix: missing jpg content type breaks corrupts presentation for Office365

- dist/pptxgen.js
New feature to allow labels to be added on Scatter Charts. Should resolve issues #410 and #291 
The following options are used for labelling scatter charts:
```
showLabel:true // Must be set to true or labels will not be shown
dataLabelFormatScatter: custom // Can be set to custom (default), customXY, or XY. 
```
There are 3 different formats that the label can be set as, and defined using dataLabelScatterFormat:
- custom - Any custom string, can be unique per plot. e.g. 'My Label'
- customXY - Any custom string with the XY plot coordinates appended. e.g. 'My Label (X,Y)'
- XY - Uses the XY plot coordinates as the label. e.g X, Y
For customXY and XY, the plot references are dynamic and will update if the underlying excel data is updated.
Data labels are applied to the Y-Values, and …
> New Feature: Add Data Labels to Scatter Charts

- dist/pptxgen.js
strXmlParaSpc needs to be after strXmlLnSpc in order for them both to take effect.
Observed bug:
Using linespacing in conjunction with paragraph spacing causes linespacing to be ignored in powerpoint for mac. (I didn't test other versions)
Example code to showcase this bug and the fix:
```
var PptxGenJS = require('./dist/pptxgen');
var pptx = new PptxGenJS();
var slide = pptx.addNewSlide();
slide.addText('Hello World!', { x:1.5, y:1.5, fontSize:18, lineSpacing: 24, paraSpaceBefore: 8 });
pptx.save('Sample Presentation');
```
open "Sample Presentation" with powerpoint,
click inside "Hello World"
choose Paragraph from the format menu
with the fix you should see Spacing Before as 8, and Line Spacing as 24.
without the fix you should see Spacing Before as 8, and Line Spacing as 0
Also I …
> fix ordering of paragraph properties

- dist/pptxgen.js
Bugfix for issue #465
Possible that it also resolves #454 but need more info from OP
When at least 1 hyperlink is included on a slide with another object such as a chart, image, video, audio etc, it creates a duplicate relationship ID as seen in the slide#.xml.rels file which leads to a corruption warning when opening the file.
Fix is to modify the var intRels = 1; to start counting from 0 when creating hyperlink rels.
I've tested with a variety of combinations
Sample Test Code - ( It's not pretty, works as proof of concept )
```
var pptx = new PptxGenJS();
var slide = pptx.addNewSlide();
// EX: Hyperlink: Web
slide.addText(
[{
text: 'PptxGenJS Project',
options: { hyperlink:{ url:'https://github.com/gitbrent/pptxgenjs', tooltip:'Visit Homepage' } }
}],
{ x:1.0, y:1.0, w:5, h:1 }
);
// …
```
> BugFix: Hyperlinks causing duplicate relationship ID when other objects on page

- dist/pptxgen.js
Adds a new chart option: valAxisCrossesAt
This allows you to specify where the Category axis crosses the Value Axis.
Acceptable values are:
1. autoZero - Default if not entered
2. max
3. A number within the range of the Value Axis min and max value
> New Chart Option: valAxisCrossesAt

- dist/pptxgen.js
PR for Issue: #470 
Update the getSmartParseNumber function to use parseFloat instead of parseInt.
When defining heights and widths that use a percentage with a decimal number it use causing minor layout issues due the decimal component being dropped.
Sample code to produce layout issue:
```
var pptx = new PptxGenJS();
var slide = pptx.addNewSlide();
slide.addShape(pptx.shapes.RECTANGLE, { x:0, y:1, w:0.87, h:1, fill:'FF0000' });
slide.addShape(pptx.shapes.RECTANGLE, { x:1, y:1, w:0.87, h:1, fill:'FF0000' });
slide.addShape(pptx.shapes.RECTANGLE, { x:2, y:1, w:0.87, h:1, fill:'FF0000' });
slide.addShape(pptx.shapes.RECTANGLE, { x:3, y:1, w:0.87, h:1, fill:'FF0000' });
slide.addShape(pptx.shapes.RECTANGLE, { x:4, y:1, w:0.87, h:1, fill:'FF0000' });
slide.addShape(pptx.shapes.RECTANGLE, { …
```
> Issue 470 - Formatting issues when using percentages

- README.md
This links (1) to prior answers tagged `PptxGenJS` and (2) to a new question template including the `PptxGenJs` tag.
> Link directly to the StackOverflow PptxGenJS tag

- package.json
So that TypeScript projects can actually use the existing typings defined in the project.
> Adds typings reference to package.json

- package.json
On the latest Typescript, I couldn't get the Typescript compiler or VS Code to recognize that the `pptxgenjs` library had a typings file. 
Adding this `types` key [seems to be required](https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html) if the `*.d.ts` file isn't at the root of the project.
Thanks for maintaining this project!
> Add types key to package.json

- src/gen-xml.ts
because PowerPoint will consider floating point values in the xml file as invalid value
> Round margin values

- package.json
When I cloned this repo down there were no types included since they are no longer in the `dist` directory. This will include them in the downloaded package files.
> Include types in package.json files

- src/core-interfaces.ts
- types/index.d.ts
This type is listed in the documentation and does work, but was not in the types file. I think these are the only two places it's needed to be added?
> Add missing margin type from ITextOpts

- src/core-interfaces.ts
- types/index.d.ts
I broke the build when I added the `margin?: number` type. It should be of `Margin` type. My mistake! Build should work now.
> Fix margin type in ITextOpts

- src/gen-objects.ts
Currently when adding multiple master slides with background images, their background image is being overwritten with the last master slide's background image. Fixes issue #663
> Add the slide layout name to the generated background image name

- src/pptxgen.ts
The code used promises, but in most cases dropped errors and rejects "on the floor", rather than just
exposing them further to the caller. This made it impossible to actually catch these problems, leading
to NodeJS warnings about "unhandled promise rejections" (which will soon make the NodeJS process
crash!)
---
This is related to https://github.com/gitbrent/PptxGenJS/issues/678, and at least allows to catch the errors.
The fixes follow a couple of patterns:
1. Remove useless wrapping promises when there is already one available
```js
return new Promise((resolve, _reject) => doSomePromiseCode.then((result) => resolve(result)))
```
This can be written as simply `return doSomePromiseCode`, which also makes the caller able to handle the rejection.
2. Move the use of `new Promise()` calls for …
> Handle errors with promise rejections

- types/index.d.ts
Removed `Buffer` to work with Angular
`Buffer` is a node.js datatype. It's not supported in Angular.
Without this fix you get the following errormessage, if you use it with angular:
`ERROR: node_modules/pptxgenjs/types/index.d.ts(67,50): error TS2591: Cannot find name 'Buffer'. Do you need to install type definitions for node? Try `npm i @types/node` and then add `node` to the types field in your tsconfig.`
fixes #654
> Removed Buffer

- src/gen-charts.ts
Since it's possible and looks nicer to set a number format (in my case: thousands separators) for the value axis labels, it seems prudent to allow setting the same format code for values in the data table as well.
fixes #489
> Add option to set the format code of chart data tables

- src/gen-charts.ts
If a secondary axis is not defined in the settings it is possible for multiple charts to use the same val axis.  
This change updates the secondary param check to only throw an exception if a secondary axis is defined.
> Fix secondary axis param check

- src/gen-objects.ts
Currently [line 280](https://github.com/gitbrent/PptxGenJS/blame/ba2c5f9b424c7ae61a77f6e9e5a659dfcb1aa59f/src/gen-objects.ts#L280) will overwrite [line 279](https://github.com/gitbrent/PptxGenJS/blame/ba2c5f9b424c7ae61a77f6e9e5a659dfcb1aa59f/src/gen-objects.ts#L279) if the chart type is PIE or DONUT.
What I did was add a conditional check, mimicking the pattern of [line 278](https://github.com/gitbrent/PptxGenJS/blame/ba2c5f9b424c7ae61a77f6e9e5a659dfcb1aa59f/src/gen-objects.ts#L278) to see if `dataLabelFormat` code is set, and I also moved this check up above the non-conditioned `dataLabelFormatCode`.
Fixes https://github.com/gitbrent/PptxGenJS/issues/803
> Fix logic for dataLabelFormat code in Pie and Donut charts

- src/gen-charts.ts
I ran into this code just by chance. Not sure how it did not error out before? I think this is what it was intended to do? Before the string was not being added to the `strXml`
> Fix data label position for Pie chart

- src/gen-xml.ts
Adds support for setting the color of a hyperlink text and resolves issues #389 
Tested against demo tests and generates all successfully and error free.
No additional user settings. relies on existing text color options. Sample code below:
```javascript
var slide = pptx.addSlide();
slide.addText(
[
{ text:'Did You Know?', options:{ fontSize:48, color:pptx.SchemeColor.accent1, breakLine:true } },
{ text:'Hyperlinks', options:{ fontSize:24, breakLine:false, color:'ff0000', hyperlink: { url: "https://github.com/gitbrent/pptxgenjs", tooltip: "Visit Homepage" }
} },
{ text:' can now be in color', options:{ fontSize:24, color:pptx.SchemeColor.accent6 } }
],
{ x:1, y:1, w:'80%', h:1.5, align:'center', fill:pptx.SchemeColor.background2 }
);
slide.addText('Hyperlinks can also be a whole …
```
> Issues #389 - Change Hyperlink Color

- src/gen-charts.ts
Fixes #834 
Fixed a bug where using double quotation marks `(" ")` in the
`valAxisLabelFormatCode` property caused the file to be corrupted.
According to _Microsoft_ documentation,
Double quotation marks are required in order to display both text
and numbers in a label. Therefore we enclose these text characters in
double quotation marks `(" ")`.
> fix(#834): Fixed data label corruption bug

- types/index.d.ts
Just removed some redundant types and fix `fill` typing, cause it is can also be a string, not only an object
> Improve types

- src/core-interfaces.ts
- src/gen-objects.ts
- src/gen-xml.ts
- types/index.d.ts
update`TextPropsOptions`
```typescript
interface TextPropsOptions {
/**
* line spacing by pt. e.g.: 28 means 28pt
*/
lineSpacing?: number
/**
* line spacing by multiple. e.g.: 1.2
*/
lineSpacingMultiple?: number
}
```
> support line spacing by multiple

- src/core-interfaces.ts
- src/gen-xml.ts
- types/index.d.ts
Added softBreakBefore to TextOptions it in [src/core-interfaces.ts](https://github.com/memorsolutions/PptxGenJS/blob/a2cd59bc97c899d881a8fdcf594c6572183d8b12/src/core-interfaces.ts#L261)  and [types/index.d.ts](https://github.com/memorsolutions/PptxGenJS/blob/a2cd59bc97c899d881a8fdcf594c6572183d8b12/types/index.d.ts#L1214) along with simple logic in [genXmlTextBody](https://github.com/memorsolutions/PptxGenJS/blob/55f680e4d9f4e7e34059b57ce9e9500a855ef36e/src/gen-xml.ts#L1232) to insert "<a:br/>" if it is set.
Implements #805
> Add option to insert soft breaks

- src/core-interfaces.ts
- src/gen-xml.ts
- types/index.d.ts
- support underline type and color
- support strike type
- support baseline
> more text style: underline/strike/baseline

- src/gen-objects.ts
- src/gen-utils.ts
- types/index.d.ts
Fix ability to specify background of slide with colour object.
```js
slide.background = { fill: { color: '909090', transparency: 50 } }
```
> Add transparency to slide

- src/gen-xml.ts
Right now there is no way to use `transparency` for `line`:
```js
slide.addShape(pptx.shapes.OVAL_CALLOUT, {
x: 6,
y: 2,
w: 3,
h: 2,
fill: { color: "ff0000", transparency: 50 },
line: { color: "000000", width: 10, transparency: 50 },
});
```
This PR will fix it
> Add transparency to line

- src/core-interfaces.ts
- src/gen-xml.ts
- types/index.d.ts
Mac has this option. Windows do not has this option. But highlight works for windows.
> text run background color (i.e. highlight)

- src/core-interfaces.ts
- src/gen-charts.ts
- src/gen-objects.ts
This update addresses a number of the outstanding bugs and requests for working with Charts.
Issue #858 :
1. Added a new configuration option: serAxisLineColor
2. Added support to use schemeColor on Category Axis Label (catAxisLabelColor)
3. Added support to use schemeColor on Category Axis Line (catAxisLineColor)
4. Added support to use schemeColor on Value Axis Label (valAxisLabelColor)
5. Added support to use schemeColor on Value Axis Line (valAxisLineColor)
6. Added support to use schemeColor on Series Axis Label (serAxisLabelColor)
7. Added support to use schemeColor on Series Axis Line (serAxisLineColor)
8. Added support to use schemeColor on Chart Title (titleColor)
9. Added support to use schemeColor on Category Axis Title (catAxisTitleColor)
10. Added support to use schemeColor …
> Multiple Chart Enhancements and Bugfixes

- src/gen-charts.ts
The format codes generated by Powerpoint often contain quotes, and so this ensures that they generate valid XML.
e.g. the default currency formatter used by Powerpoint is `_(" $"* #,##0.00_);_(" $"* \(#,##0.00\);_(" $"* " -"??_);_(@_)`
> Use encodeXmlEntities for formatCode attributes

- src/core-interfaces.ts
- src/gen-charts.ts
For bar chart with "clustered" grouping only
> Added overlap parameter to bar charts

- src/gen-xml.ts
Handle bold from TextBaseProps by setting `b="1"` in the XML. Move up align definition before the field as it was no longer working when combined with bold.
Add actual slide number in the XML so that LibreOffice displays the slide number too (actually solves #339).
> Allow slide number to be set as bold

- src/core-interfaces.ts
- src/gen-charts.ts
- types/index.d.ts
invertedColors should be defined as "HexColor[]";
bar chart did not render inverted colored negative bars unless more than one color was provided in the chartColors array
> Fix for `InvertedColors` (Issue #970)

- src/gen-charts.ts
Doughnut charts display a single "Serie 1" label in their legend on
OpenOffice. This is due to `varyColor` (or "Vary Colors By Point") being
set to 0 on them. Since doughnut charts always have one color per
"point" (area), this should always be set to 1 for them.
> bugfix: each data marker on a doughnut as a different color

- src/core-interfaces.ts
- src/gen-objects.ts
- src/gen-xml.ts
Added transparency support for the Image.
Will close https://github.com/gitbrent/PptxGenJS/issues/773
API:
```js
slide.addImage({ data: SVG_BASE64, x: 11.1, y: 5.1, w: 1.5, h: 1.5, transparency: 50 });
```
> Image: Add transparency

- src/core-enums.ts
- src/gen-charts.ts
- src/gen-objects.ts
Support bubble chart with a 3D appearance for bubbles instead of a solid display.
Implementation is done as a new chart type as Powerpoint UI defines it as a different type and bar 3D is defined as its own type as well. I'm not sure it is the best way, especially as even though Powerpoint UI treats it as a different chart type, in the XML it is a bubble chart with an option set to `1`. An alternative could be with a property (like `bubble3d: boolean` or `bubbleAppearence = 'solid' | '3d'`) but there is no existing type for bubble chart specific options.
If you prefer that setting to be done in any way feel free to tell and I will update the PR accordingly.
> Support bubble 3D chart type

- src/gen-charts.ts
Object name is escaped at one place, but missing on another.
> bugfix: escape object name in chart xml

- src/core-interfaces.ts
- src/gen-charts.ts
The goal is to actually display a label aside each bubble. Adding a label per bubble requires generating a lot of XML: adding a new column with label as data, and data references to these labels.
Adding serie name is much easier, only setting a flag. The trick is then to create one serie per bubble: X axis contains the positions of all bubbles, then each serie contains a single value. It also allows setting the color for each bubble, again without complex generation.
| X Axis | Serie 1 | Size 1 | Serie 2 | Size 2 | Serie 3 | Size 3 |
|--------|---------|--------|---------|--------|---------|--------|
| 1.5    | 2.5     | 100    |         |        |         |        |
| 2      |         |        | 1.2     | 50     |         |        |
| 2.3    |         |        |         |        | 3.2 …
> serie name on bubble chart, category axis position, leader lines on bubble chart

- docs/api-images.md
The `transparency` property is available for images but is missing from the API doc. Info taken from `core-interfaces.ts`
> Update image API doc

- docs/api-text.md
Add missing properties to text API docs:
- `transparency`
- `wrap`
These are already supported by the lib, but were still missing from the documentation.
> Update text docs: transparency + wrap

- src/gen-charts.ts
Doughnut chart ignores holeSize=0 as a falsy value and takes is default of 50.
Code now checks the type of holeSize to treat 0 as a number and display doughnuts with no hole at all.
This leads to a chart very similar to a pie chart, but means that we do not have to change chart type for the 0 special case.
> bugfix: handle holeSize=0 for doughnut chart

- demos/browser/index.html
- demos/modules/demo_image.mjs
- src/core-interfaces.ts
- src/gen-objects.ts
- src/gen-utils.ts
- src/gen-xml.ts
**Description**
This PR takes the shape shadow implementation and adapts it to images.
Related to [Issue #986](https://github.com/gitbrent/PptxGenJS/issues/986)
**Example**
```js
let pptx = new PptxGenJS();
let slide = pptx.addSlide();
slide.addImage({
x: 1,
y: 1,
path: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwyMTIyMnwwfDF8c2VhcmNofDJ8fGxhbmRzY2FwZXxlbnwwfHx8fDE2NTg5MzE0MDM&ixlib=rb-1.2.1&q=80&w=1080",
shadow: {
type: "outer",
angle: 90,
blur: 10,
color: "000000",
offset: 4,
opacity: 0.5
}
});
pptx.writeFile({ fileName: "PptxGenJS-Sandbox.pptx" });
```
Sample PPT files:
[PptxGenJS-Shadows.pptx](https://github.com/gitbrent/PptxGenJS/files/9308201/PptxGenJS-Shadows.pptx) …
> Add optional image shadow props
